### PR TITLE
Add rbac and psp

### PR DESCRIPTION
**Pull request by pipo02mix**
Towards [#2296](https://github.com/giantswarm/giantswarm/issues/2296)

Add RBAC according to k8s API methods used on the project

### CODE REVIEW

**Comment by MarcelMue** [comment]
What is the reason for not splitting the RBAC file into multiple files? I think it's easier to find something if files are split WDYT?

**Comment by pipo02mix** [comment]
I agree it has some advantages. I have seen both approaches in the community. We can discuss it I dont have a strong position here. IMO have it just one file with the role and the binding together is more useful than split between different files

**Comment by puja108** [comment]
I'm not very emotional on this, upside of single file is that you clearly see how it works together, downside may only be a bit of reusability maybe? not sure, the thing is these files should always go together, they don't make much sense without each other

**Comment by pipo02mix** [comment]
Right now we have usually two roles and two bindings (1 for k8s resources and 1 for psp use). What we can do is when we add more roles/bindings and eventually we find is hard to manage in a single file then we split in more. WDYT @MarcelMue ?

**Comment by MarcelMue** [comment]
I personally like putting stuff into separated files and if they belong together we should have them in an appropriate subfolder. No hard feelings though.

Let's go with this structure and if we hit ~300 lines we should think about splitting IMO.

**Pull request merged**
